
<h2>Login</h2>

<form action="<?= url('/478845ZrqQifzZ9ymRHF_login/access') ?>" method="POST">
    <div class="adminForm">
        <label for="username">User name</label>    
            <input type="text" class="userName" name="username" placeholder="user name">
        <label for="email">Email</label>
            <input type="email" class="userEmail" name="email" placeholder="email">
        <label for="password">Password</label>
            <input type="password" class="password" name="password" placeholder="password">
        
        <button class="submit">Submit</button>

    </div>
</form>
