<div>
        <ul class="superAdmin">
            <a href="<?= url('/super-admin-control') ?>"><li>All Booking</li></a>
            <a href="<?= url('/booking') ?>"><li>Add Booking</li></a>
        </ul>
    </div>

<h2>New Admin</h2>


<form action="#" method="post">
    <label for="login"></label>
    <p></p>
    <input type="text" id="addUserName" name="Nom" placeholder="user name">
    <p></p>
    <input type="email" id="addUserEmail" name="email" placeholder="email">
    <p></p>
    <input type="password" id="addPassword" name="password" placeholder="password">
    <p></p>
    <input type="password" id="confirmPassword" name="confirmPassword" placeholder="confirm password">
    <p></p>
    <button id="addAccess">Submit</button>

</form>