

<h2>New Admin</h2>


<form action="<?= url('/addAdmin/create') ?>" method="POST">
    <div class="adminForm">
    <label for="userName">User name</label>
    
    <input type="text" class="userName" name="userName" placeholder="user name" value="<?php if(isset($errors['data'])&& $errors['data']['userName'] !=='') 
        {
            echo ($errors['data']['userName']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['userName']!=='')
        {
            echo($errors['message']['userName']);
        }
    ?>
    </small></p>

    <select name="userStatus" class="status">
        
    <option value="">choose status</option>
    <option value="admin">admin</option>
    <option value="super admin">super admin</option>

    </select>
    <p><small class="errorForm">
                                
                        <?php
                            if(isset($errors['message']) && $errors['message']['userStatus']!=='')
                            {
                                echo($errors['message']['userStatus']);
                            }
                        ?>
                            </small></p>

    <label for="email">Email</label>
    
    <input type="email" class="userEmail" name="email" placeholder="email" value="<?php if(isset($errors['data'])&& $errors['data']['email'] !=='') 
        {
            echo ($errors['data']['email']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['email']!=='')
        {
            echo($errors['message']['email']);
        }
    ?>
    </small></p>

    <label for="password">Password</label>
    
    <input type="password" class="password" name="password" placeholder="password" value="<?php if(isset($errors['data'])&& $errors['data']['password'] !=='') 
        {
            echo ($errors['data']['password']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['password']!=='')
        {
            echo($errors['message']['password']);
        }
    ?>
    </small></p>

    <label for="password">Confirm your password</label>
    
    <input type="password" class="confirmPassword" name="confirmPassword" placeholder="confirm password" value="<?php if(isset($errors['data'])&& $errors['data']['confirmPassword'] !=='') 
        {
            echo ($errors['data']['confirmPassword']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['confirmPassword']!=='')
        {
            echo($errors['message']['confirmPassword']);
        }
    ?>
    </small></p>
    
    <button class="submit">Submit</button>
    </div>
</form>