<div>
        <ul class="superAdmin">
            <a href="<?= url('/super-admin-control') ?>"><li>All Booking</li></a>
            <a href="<?= url('/booking') ?>"><li>Add Booking</li></a>
        </ul>
    </div>

<h2>New Admin</h2>


<form action="#" method="post">
    <div class="adminForm">
    <label for="add"></label>
    
    <input type="text" id="addUserName" name="userName" placeholder="user name">

    <select name="status" id="status">
    <option value="admin">admin</option>
    <option value="super admin">super admin</option>
    </select>
    
    <input type="email" id="addUserEmail" name="email" placeholder="email">
    
    <input type="password" id="addPassword" name="password" placeholder="password">
    
    <input type="password" id="confirmPassword" name="confirmPassword" placeholder="confirm password">
    
    <button id="addAccess">Submit</button>
    </div>
</form>