
    <table class="table">
    <thead>
        <tr>
            <th>Number</th>
            <th>id booking</th>
            <th>customer id</th>
            <th>LastName</th>
            <th>FirstName</th>
            <th>birthdate</th>
            <th>category</th>
            <th>check-in</th>
            <th>check-out</th>
            <th>Created at</th>
            <?php if($_SESSION['user']['userstatus'] === 'super admin'): ?>
            <th colspan="2">Action</th>
            <?php endif ?>
        </tr>
    </thead>
        <tbody>
            <!-- boucle permettant d'afficher le detail de chaque booking -->
            <?php foreach ($booking as $book): ?>
                <tr>
                    <td class="nbr"></td>
                    <td><?= htmlspecialchars($book['id_booking']) ?></td>
                    <td><?= htmlspecialchars($book['cust_id']) ?></td>
                    <td><?= htmlspecialchars($book['cust_lastname'])  ?></td>
                    <td><?= htmlspecialchars($book['cust_firstname']) ?></td>
                    <td><?= htmlspecialchars(date_format(date_create(($book['cust_birthdate'])), 'd/m/Y'))?></td>
                    <td><?= htmlspecialchars($book['cat_title']) ?></td>
                    <td><?= htmlspecialchars(date_format(date_create(($book['check_in'])), 'd/m/Y')) ?></td>
                    <td><?= htmlspecialchars(date_format(date_create(($book['check_out'])), 'd/m/Y')) ?></td>
                    <td><?= htmlspecialchars(date_format(date_create(($book['created_at'])), 'd/m/Y H:i:s')) ?></td>
                    <!-- condition pour donner accès uniquement aux "super admin" -->
                    <?php if($_SESSION['user']['userstatus'] === 'super admin'): ?>
                    <!-- lien vers le formulaire "updateBooking" avec la variable $book et sa clé qui contient le bon "id" pour le modifier le bon booking et/ou le bon customer  -->
                    <td><a href="<?= url('/bookingList/updateBooking', ['cust_id' => $book['cust_id'], 'id_booking' => $book['id_booking']]) ?>">Update</a></td>
                    <!-- lien vers la méthode "delete" avec la variable $book et sa clé qui contient le bon "id" pour supprimer le bon booking -->
                    <td><a href="<?= url('/bookingList/delete', ['id' => $book['cust_id']]) ?>">Delete</a></td>
                    <?php endif ?>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    <script src="../assets/js/nbr.js"></script>



    


    
            

                    
                
