
<!-- page booking, formulaire séparer en 2 parties -->
<h2>Booking</h2>

    <h3>Personal details</h3>

        <form action="<?= url('/booking/create') ?>" method="POST">
            <div class="classForm">
                
                    <div class="div-input">
                        <label for="firstName">First name</label>

                            <input type="text" name="firstName" class="firstName" placeholder="Your first name" value="<?php if(isset($errors['data'])&& $errors['data']['firstName'] !=='') 
                            {
                                // si $errors 'data' est defini et que $errors 'data','firstName' n'est pas vide
                                // alors réaffichage de la donnée entrée précédement avant le déclenchement des erreurs
                                echo ($errors['data']['firstName']);
                            }
                            ?>"> 
                            <p><small class="errorForm">
                        <?php
                            // si $errors 'message' est défini et que $errors 'message','firstName' n'est pas vide
                            if(isset($errors['message']) && $errors['message']['firstNameEmpty']!=='')
                            {
                                // alors affichage du message d'erreur 'firstName' defini dans le controller
                                echo($errors['message']['firstNameEmpty']);
                            }
                            else if (isset($errors['message']) && $errors['message']['firstName']){
                                echo($errors['message']['firstName']);
                            }
                        ?>
                        </small></p>
                    </div>
                    <div class="div-input">
                        <label for="lastName">Last name</label>

                            <input type="text" name="lastName" class="lastName" placeholder="Your last name" value="<?php if(isset($errors['data'])&& $errors['data']['lastName'] !=='') 
                            {
                                echo ($errors['data']['lastName']);
                            }?>"> 
                            <p><small class="errorForm">
                        <?php
                            if(isset($errors['message']) && $errors['message']['lastNameEmpty']!=='')
                            {
                                echo($errors['message']['lastNameEmpty']);
                            }
                            else if (isset($errors['message']) && $errors['message']['lastName']){
                                echo($errors['message']['lastName']);
                            }
                        ?>
                            </small></p>
                    </div>
                    <div class="div-input">
                            <label for="email">Email</label>

                                <input type="email" name="email" class="email" placeholder="Your email" value="<?php if(isset($errors['data'])&& $errors['data']['email'] !=='') 
                                {
                                    echo ($errors['data']['email']);
                                }?>"> 
                                <p><small class="errorForm">
                            <?php
                                if(isset($errors['message']) && $errors['message']['email']!=='')
                                {
                                    echo($errors['message']['email']);
                                }
                            ?>
                                </small></p>
                    </div>                    
                                           
                    <div class="div-input-label">
                            <div><label for="birthDate">Birthdate</label></div>
                            
                                <input type="date" name="birthDate" class="birthDate" placeholder="Your birth date" value="<?php if(isset($errors['data'])&& $errors['data']['birthDate'] !=='') 
                                {
                                    echo ($errors['data']['birthDate']);
                                }?>">
                                <p><small class="errorForm">
                            <?php
                                if(isset($errors['message']) && $errors['message']['birthDate']!=='')
                                {
                                    echo($errors['message']['birthDate']);
                                }
                            ?>
                                </small></p>
                    </div>
            </div>
            
            <hr>
            
            <h3>Your stay</h3>
                <div class="formRoom">
                    
                        <div><label for="check-in">Check-in: 2pm</label></div>
                        
                            <input type="date" class="check-in" name="check_in" value="<?php if(isset($errors['data'])&& $errors['data']['check_in'] !=='') 
                            {
                                // si $errors 'data' est defini et que $errors 'data','check_in' n'est pas vide
                                // alors réaffichage de la date entrée précédement avant le déclenchement des erreurs
                                echo ($errors['data']['check_in']);
                            }?>">
                            <p><small class="errorForm">
                        <?php
                            // si $errors 'message' est défini et que $errors 'message','check_in' n'est pas vide
                            if(isset($errors['message']) && $errors['message']['check_in']!=='')
                            {
                                // alors affichage du message d'erreur 'check_in' defini dans le controller
                                echo($errors['message']['check_in']);
                            }
                        ?>
                            </small></p>
                        
                        <div><label for="check-out">Check-out: 12am</label></div>
                        
                            <input type="date" class="check-out" name="check_out" value="<?php if(isset($errors['data'])&& $errors['data']['check_out'] !=='') 
                            {
                                echo ($errors['data']['check_out']);
                            }?>">
                            <p><small class="errorForm">
                        <?php
                            if(isset($errors['message']) && $errors['message']['check_out']!=='')
                            {
                                echo($errors['message']['check_out']);
                            }
                        ?>
                            </small></p>
                       
      
                        <h3>Your room</h3>
                        
                        <select class="selectCategory" name="cat_id">
                            
                            <option value="">Choose your room</option>
                                <!-- boucle pour faire afficher les catégories de rooms -->
                                <?php foreach ($rooms as $room): ?>
                                    
                                    <option class="catDisplay"value="<?= htmlspecialchars($room['cat_id']) ?>"
                                    
                                    <?php if(isset($errors)): ?>

                                        <?php if ($errors['data']['cat_id'] == $room['cat_id']) : ?> selected <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    
                                    ><?= htmlspecialchars($room['cat_title']) ?></option>
                                <?php endforeach ?>
                                
                        </select>
                            <p><small class="errorForm">
                                
                        <?php
                            if(isset($errors['message']) && $errors['message']['cat_id']!=='')
                            {
                                echo($errors['message']['cat_id']);
                            }
                        ?>
                            </small></p>
                            
                        
                    <div class="result">

                        <div class="price">
                            <span class="priceDisplay"></span>
                        </div>
                        <div class="days">

                        </div>
                        <div class="priceTimesDays">
                            
                        </div>
                                    
                    </div>  
                        
                </div>
                
                <button class="submit">Book now!</button>
        </form>
        
        
                
                
                