
<h2>Welcome</h2>

<div>


        <img class="imghome" src="../assets/img/hotel/n_IKQDCyrG0.jpg" alt="Photo de présentation">
    
    <section>
        <h3>We are your top luxury boutique hotel and resorts</h3>
            <article class="homeArticle">
                <p class="homeText">We wanted to provide a simple and untouched escape.
                    A perfect retreat for you to enjoy nature and spend quality time with your loved ones - or a perfect retreat while you explore a new adventure.
                    Bintana Sa Paraiso in Bisayan means “Window to Paradise”, and your paradise awaits.
                    We want to be the place where you want to stay in Camiguin.</p>
                <p class="homeText">Bintana Sa Paraiso in Naasag sits perched on a lovely hill at the foot of magnificent Mt. Hibok-Hibok.
                    What adds to this beautiful property and makes it unique is the secluded hot spring nearby, that flows gently into the pristine waters of the Bohol Sea.
                    Better get ready- this hidden gem gives you the full 90-degree view!</p>
                    <div id="slider">
                        <img src="../assets/img/hotel/2gOxKj594nM.jpg" alt="photo de presentation" id="slide">
                        <div id="precedent" onclick="ChangeSlide(-1)"><</div>
                        <div id="suivant" onclick="ChangeSlide(1)">></div>
                    </div>
                    <p class="homeText"><strong>my Hotel</strong> Step into your own private paradise at our resort.
                        Our eco-friendly resort is nestled in the belly of Mt. Hibok Hibok and offers stunning views of palm trees and the white island .
                        Enjoy a relaxing hammock session on your large balcony, or take a refreshing shower in our big bathroom with hot and cold running water.
                        Wake up to fresh mountain air and breakfast served to your room, then spend the day exploring all that <strong>my Hotel</strong> has to offer.
                        Come back to your piece of heaven at night for a delicious home cooked meal, from highly acclaimed restaurant, Joshua + Luke. You have a spectacular view of the popular white island beach while feeling like you are in the jungle.
                        Bali-inspired tiki huts and picture-worthy amenities. One of the most viewed and celebrated <strong>Island Resorts</strong>.
                        It was featured on Metro Chanel  TV Show “Beached” and home of many Travel Influencers around the world.</p>
            </article>
    </section>


</div>


<script src="../assets/js/slider.js"></script>
    
    
    
