
<h2>Connexion</h2>


<form action="#" method="post">
    <label for="login">Connexion</label>
    <p></p>
    <input type="text" id "userLastName" name="Nom" placeholder="votre Nom">
    <p></p>
    <input type="text" id "userFirstName" name="prenom" placeholder="votre prénom">
    <p></p>
    <input type="email" id "userEmail" name="email" placeholder="votre email">
    <p></p>
    <button>Soumettre</button>

</form>

<!-- <form action="index.php?route=login" method="POST">
    <input type="email" name="email" placeholder="Email..."/>
    <input type="password" name="password" placeholder="Password..."/>
    <input type="submit" value="Submit"/>
</form> -->
