
<h2>Connexion</h2>


<form action="#" method="post">
    <label for="login">Login</label>
    <p></p>
    <input type="text" id="userName" name="Nom" placeholder="user name">
    <p></p>
    <input type="email" id="userEmail" name="email" placeholder="email">
    <p></p>
    <input type="password" id="password" name="password" placeholder="password">
    <p></p>
    <button id="access">Submit</button>

</form>

<!-- <form action="index.php?route=login" method="POST">
    <input type="email" name="email" placeholder="Email..."/>
    <input type="password" name="password" placeholder="Password..."/>
    <input type="submit" value="Submit"/>
</form> -->
