
<h2>Login</h2>

<form action="<?= url('/login/access') ?>" method="POST">
    <div class="adminForm">
        <label for="username">User name</label>    
        <input type="text" class="userName" name="username" placeholder="user name">
        <label for="email">Email</label>
        <input type="email" class="userEmail" name="email" placeholder="email">
        <label for="password">Password</label>
        <input type="password" class="password" name="password" placeholder="password">
        
        <button class="submit">Submit</button>

    </div>
</form>
<!-- <form action="index.php?route=login" method="POST">
    <input type="email" name="email" placeholder="Email..."/>
    <input type="password" name="password" placeholder="Password..."/>
    <input type="submit" value="Submit"/>
</form> -->
