
<h2 class="roomsTitle">Rooms</h2>

    <section class="rooms">

        
        <?php foreach ($rooms as $room): ?>
            
            <hr>

                <div class="wrapper">
                    <h3 class="roomsTitle"><?= $room['cat_title'] ?></h3>
                    <?php foreach ($pictures as $picture): ?>
                        <?php if($room['cat_id'] == $picture['cat_id']):?>                        
                            <a href="../assets/img/<?= $room['cat_id'] ?>/<?= $picture['picture_url'] ?>" data-fancybox="gallery">
                                <img class="picRoom" src="../assets/img/<?= $room['cat_id'] ?>/<?= $picture['picture_url'] ?>" alt=""></a>                        
                        <?php endif ?>
                    <?php endforeach ?>
                    <p class="roomDescription"><?= $room['cat_description'] ?></p>
                    <p><?= $room['cat_price'] ?>€</p>
                </div>
            
            
        <?php endforeach ?>
              
            
        

    </section>

    
        

