

    <div>
        <ul class="superAdmin">
            <a href="<?= url('/super-admin-control') ?>"><li>All Booking</li></a>
            <a href="<?= url('/booking') ?>"><li>Add Booking</li></a>
            <a href="<?= url('/addAdmin') ?>"><li>Add Admin</li></a>
        </ul>
    </div>

    <table class="table">
    <thead>
        <tr>
            <th>Number</th>
            <th>id booking</th>
            <th>customer id</th>
            <th>LastName</th>
            <th>FirstName</th>
            <th>birthdate</th>
            <th>category</th>
            <th>check-in</th>
            <th>check-out</th>
            <th>Created at</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
        <tbody>
            <?php foreach ($booking as $book): ?>
            <tr>

                    <td id="nbr"></td>
                    <td><?= $book['id_booking'] ?></td>
                    <td><?= $book['cust_id'] ?></td>
                    <td><?= $book['cust_lastname'] ?></td>
                    <td><?= $book['cust_firstname'] ?></td>
                    <td><?= date_format(date_create(($book['cust_birthdate'])), 'd/m/Y')?></td>
                    <td><?= $book['cat_title'] ?></td>
                    <td><?= date_format(date_create(($book['check_in'])), 'd/m/Y')?></td>
                    <td><?= date_format(date_create(($book['check_out'])), 'd/m/Y')?></td>
                    <td><?= date_format(date_create(($book['created_at'])), 'd/m/Y H:i:s')?></td>
                    <td><a href="<?= url('/super-admin-control/updateBooking', ['cust_id' => $book['cust_id'], 'id_booking' => $book['id_booking']]) ?>">Update</a></td>
                    <td><a href="<?= url('/super-admin-control/delete', ['id' => $book['cust_id']]) ?>">Delete</a></td>

                </tr>
                <?php endforeach ?>
        </tbody>
    </table>

    
            

                    
                
