
<h2 class="titleAdmin">Admin space</h2>
    <div>
        <ul class="superAdmin">
            <a href="<?= url('/super-admin-control') ?>"><li>Booking</li></a>
            <a href="<?= url('/super-admin-control') ?>"><li>Add</li></a>
        </ul>
    </div>

    <table class="table">
    <thead>
        <tr>
            <th>Number</th>
            <th>id booking</th>
            <th>customer id</th>
            <th>LastName</th>
            <th>FirstName</th>
            <th>category</th>
            <th>check-in</th>
            <th>check-out</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
        <tbody>
            <?php foreach ($booking as $book): ?>
            <tr>

                    <td></td>
                    <td><?= $book['id_booking'] ?></td>
                    <td><?= $book['cust_id'] ?></td>
                    <td><?= $book['cust_lastname'] ?></td>
                    <td><?= $book['cust_firstname'] ?></td>
                    <td><?= $book['cat_title'] ?></td>
                    <td><?= $book['check_in'] ?></td>
                    <td><?= $book['check_out'] ?></td>
                    <td><a href="<?= url('/super-admin-control') ?>">Update</a></td>
                    <td><a href="<?= url('/super-admin-control') ?>">Delete</a></td>

                </tr>
                <?php endforeach ?>
        </tbody>
    </table>
            

                    
                
