

<h2>Update</h2>


<form action="<?= url('/users/update') ?>" method="POST">
    <input type="hidden" name="user_id" value= "<?= $user['user_id'] ?>">
    <div class="adminForm">
    <label for="user"></label>
    
    <input type="text" class="userName" name="userName" placeholder="user name" value="<?= htmlspecialchars($user['user_name']) ?><?php if(isset($errors['data'])&& $errors['data']['userName'] !=='') 
        {
            echo ($errors['data']['userName']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['userName']!=='')
        {
            echo($errors['message']['userName']);
        }
    ?>
    </small></p>

    <select name="userStatus" class="status">

    <option value="<?= htmlspecialchars($user['user_status'])?>"><?= htmlspecialchars($user['user_status'])?></option>
    <option value="admin">admin</option>
    <option value="super admin">super admin</option>

    </select>
    <p><small class="errorForm">
                                
                        <?php
                            if(isset($errors['message']) && $errors['message']['userStatus']!=='')
                            {
                                echo($errors['message']['userStatus']);
                            }
                        ?>
                            </small></p>
    
    <input type="email" class="userEmail" name="email" placeholder="email" value="<?= htmlspecialchars($user['user_email'])?><?php if(isset($errors['data'])&& $errors['data']['email'] !=='') 
        {
            echo ($errors['data']['email']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['email']!=='')
        {
            echo($errors['message']['email']);
        }
    ?>
    </small></p>
    
    <input type="password" class="password" name="password" placeholder="password" value="<?= htmlspecialchars($user['user_password']) ?><?php if(isset($errors['data'])&& $errors['data']['password'] !=='') 
        {
            echo ($errors['data']['password']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['password']!=='')
        {
            echo($errors['message']['password']);
        }
    ?>
    </small></p>
    
    <input type="password" class="confirmPassword" name="confirmPassword" placeholder="confirm password" value="<?= htmlspecialchars($user['user_password']) ?><?php if(isset($errors['data'])&& $errors['data']['confirmPassword'] !=='') 
        {
            echo ($errors['data']['confirmPassword']);
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        if(isset($errors['message']) && $errors['message']['confirmPassword']!=='')
        {
            echo($errors['message']['confirmPassword']);
        }
    ?>
    </small></p>
    
    <button class="addAccess">Submit</button>
    </div>
</form>