

<h2>Update</h2>


<form action="<?= url('/users/update') ?>" method="POST">
    <input type="hidden" name="user_id" value= "<?= $user['user_id'] ?>">
    <div class="adminForm">
    <label for="user"></label>
    
    <input type="text" class="userName" name="userName" placeholder="user name" value="<?= htmlspecialchars($user['user_name']) ?><?php if(isset($errors['data'])&& $errors['data']['userName'] !=='') 
        {
            // chargement de la donnée $user'userName' à modifier
            // puis si $errors 'data' est defini et que $errors 'data','userName' n'est pas vide
            // alors réaffichage de la donnée gérer par le controller
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        // si $errors 'message' est défini et que $errors 'message','userName' n'est pas vide
        if(isset($errors['message']) && $errors['message']['userName']!=='')
        {
            // alors affichage du message d'erreur 'userName' defini dans le controller
            echo($errors['message']['userName']);
        }
    ?>
    </small></p>

    <select name="userStatus" class="status">

    <option value="<?= htmlspecialchars($user['user_status'])?>"><?= htmlspecialchars($user['user_status'])?></option>
    <option value="admin">admin</option>
    <option value="super admin">super admin</option>

    </select>
    <p><small class="errorForm">
                                
    <?php
        // si $errors 'message' est défini et que $errors 'message','userStatus' n'est pas vide
        if(isset($errors['message']) && $errors['message']['userStatus']!=='')
        {
            // alors affichage du message d'erreur 'userStatus' defini dans le controller
            echo($errors['message']['userStatus']);
        }
    ?>
        </small></p>
    
    <input type="email" class="userEmail" name="email" placeholder="email" value="<?= htmlspecialchars($user['user_email'])?><?php if(isset($errors['data'])&& $errors['data']['email'] !=='') 
        {
            // chargement de la donnée $user'email' à modifier
            // puis si $errors 'data' est defini et que $errors 'data','email' n'est pas vide
            // alors réaffichage de la donnée gérer par le controller
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        // si $errors 'message' est défini et que $errors 'message','email' n'est pas vide
        if(isset($errors['message']) && $errors['message']['email']!=='')
        {
            // alors affichage du message d'erreur 'email' defini dans le controller
            echo($errors['message']['email']);
        }
    ?>
    </small></p>
    
    <input type="password" class="password" name="password" placeholder="password" value="<?= htmlspecialchars($user['user_password']) ?><?php if(isset($errors['data'])&& $errors['data']['password'] !=='') 
        {
            // chargement de la donnée $user'password' à modifier
            // puis si $errors 'data' est defini et que $errors 'data','password' n'est pas vide
            // alors réaffichage du mot de passe gérer par le controller
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        // si $errors 'message' est défini et que $errors 'message','password' n'est pas vide
        if(isset($errors['message']) && $errors['message']['password']!=='')
        {
            // alors affichage du message d'erreur 'password' defini dans le controller
            echo($errors['message']['password']);
        }
    ?>
    </small></p>
    
    <input type="password" class="password" name="confirmPassword" placeholder="confirm password" value="<?= htmlspecialchars($user['user_password']) ?><?php if(isset($errors['data'])&& $errors['data']['confirmPassword'] !=='') 
        {
            // chargement de la donnée $user'confirmPassword' à modifier
            // puis si $errors 'data' est defini et que $errors 'data','confirmPassword' n'est pas vide
            // alors réaffichage du mot de passe gérer par le controller
        }
        ?>"> 
        <p><small class="errorForm">
    <?php
        // si $errors 'message' est défini et que $errors 'message','confirmPassword' n'est pas vide
        if(isset($errors['message']) && $errors['message']['confirmPassword']!=='')
        {
            // alors affichage du message d'erreur 'confirmPassword' defini dans le controller
            echo($errors['message']['confirmPassword']);
        }
    ?>
    </small></p>
    
    <button class="submit">Submit</button>
    </div>
</form>