

<h2>Update Booking</h2>

<h3>Personal details</h3>

    <form action="<?= url('/super-admin-control/update') ?>" method="POST">
        <input type="hidden" name="cust_id" value="<?= $form['cust_id'] ?>">
        <div class="idForm">
            
                <div class="div-input">
                    <label for="firstName"></label>

                    <input type="text" name="firstName" id="firstName" placeholder="first name" value="<?= htmlspecialchars($form['cust_firstname']) ?><?php if(isset($errors['data'])&& $errors['data']['lastName'] !=='') 
                    {
                        // echo ($errors['data']['firstName']);
                    }?>"> 
                    <p><small class="errorForm"><?php
                    if(isset($errors['message']) && $errors['message']['firstName']!=='')
                    {
                        echo($errors['message']['firstName']);
                    }
                    ?></small></p>
                </div>
                <div class="div-input">
                    <label for="lastName"></label>

                    <input type="text" name="lastName" id="lastName" placeholder="last name" value="<?= htmlspecialchars($form['cust_lastname']) ?><?php if(isset($errors['data'])&& $errors['data']['lastName'] !=='') 
                    {
                        // echo ($errors['data']['lastName']);
                    }?>"> 
                    <p><small class="errorForm"><?php
                    if(isset($errors['message']) && $errors['message']['lastName']!=='')
                    {
                        echo($errors['message']['lastName']);
                    }
                    ?></small></p>
                </div>
                <div class="div-input">
                        <label for="email"></label>

                        <input type="email" name="email" id="email" placeholder="email" value="<?= htmlspecialchars($form['cust_email']) ?><?php if(isset($errors['data'])&& $errors['data']['email'] !=='') 
                        {
                        // echo ($errors['data']['email']);
                        }?>"> 
                        <p><small class="errorForm"><?php
                    if(isset($errors['message']) && $errors['message']['email']!=='')
                    {
                        echo($errors['message']['email']);
                    }
                    ?></small></p>
                </div>                    
                                       
                <div class="div-input-label">
                        <div><label for="birthdate">your birthdate</label></div>
                        
                        <input type="date" name="birthDate" id="birthDate" value="<?= htmlspecialchars($form['cust_birthdate']) ?><?php if(isset($errors['data'])&& $errors['data']['birthDate'] !=='') 
                    {
                        // echo ($errors['data']['birthDate']);
                    }?>">
                        <p><small class="errorForm"><?php
                    if(isset($errors['message']) && $errors['message']['birthDate']!=='')
                    {
                        echo($errors['message']['birthDate']);
                    }
                    ?></small></p>
                </div>
        </div>
        
        <hr>
        
        <h3>Your stay</h3>
        
            <input type="hidden" name="id_booking" value="<?= $form2['id_booking'] ?>">
            <div class="divRoom">
                
                <div><label for="check-in">Check-in: 2pm</label></div>
                    
                    <input type="date" id="check-in" name="check_in" value="<?= htmlspecialchars($form2['check_in']) ?><?php if(isset($errors['data'])&& $errors['data']['check_in'] !=='') 
                    {
                        // echo ($errors['data']['check_in']);
                    }?>">
                    <p><small class="errorForm"><?php
                    if(isset($errors['message']) && $errors['message']['check_in']!=='')
                    {
                        echo($errors['message']['check_in']);
                    }
                    ?></small></p>
                    
                <div><label for="check-out">Check-out: 12am</label></div>
                    
                    <input type="date" id="check-out" name="check_out" value="<?= htmlspecialchars($form2['check_out']) ?><?php if(isset($errors['data'])&& $errors['data']['check_out'] !=='') 
                    {
                        // echo ($errors['data']['check_out']);
                    }?>">
                    <p><small class="errorForm"><?php
                    if(isset($errors['message']) && $errors['message']['check_out']!=='')
                    {
                        echo($errors['message']['check_out']);
                    }
                    ?></small></p>
                   
  
                <h3>Your room</h3>
                    
                    <select class="selectCategory" name="cat_id">
                        
                        <option value="">Choose your room</option>
                        
                            <?php foreach ($rooms as $room): ?>
                                <option value="<?= htmlspecialchars($room['cat_id']) ?>"
                                 <?php if ($form2['cat_id'] == $room['cat_id']) : ?> selected <?php endif; ?>><?= htmlspecialchars($room['cat_title']) ?></option>
                            <?php endforeach ?>
                            
                            
                    </select>
                <p><small class="errorForm"><?php
                    if(isset($errors['message']) && $errors['message']['cat_id']!=='')
                    {
                        echo($errors['message']['cat_id']);
                    }
                ?></small></p>
                        
                    

                <div class="price">
                    
                            
                </div>
                    
                    
            </div>
            
        <button class="submit">Update</button>
    </form>
    
    
            
            
            