

<table class="table">
    <thead>
        <tr>
            <th>id</th>
            <th>user name</th>
            <th>status</th>
            <th>email</th>
            <th>created at</th>
        </tr>
    </thead>
    <tbody>
            <?php foreach ($users as $user): ?>
            <tr>

                    <td><?= $user['user_id'] ?></td>
                    <td><?= $user['user_name'] ?></td>
                    <td><?= $user['user_status'] ?></td>
                    <td><?= $user['user_email'] ?></td>
                    <td><?= date_format(date_create(($user['created_at'])), 'd/m/Y H:i:s')?></td>

                </tr>
                <?php endforeach ?>
        </tbody>
    </table>